#!/usr/bin/env bash
#Tranfer file at remote server
# Update repositories
apt-get update

# Install NGINX
apt-get install nginx -y

# Configure firewall
# Uncomment out the line that meets your needs
ufw allow 'Nginx HTTP' # port 80 only
echo "Hello World!" >/var/www/html/index.nginx-debian.html
service nginx restart