#!/usr/bin/env bash
# Replace a line with multiple lines with sed

apt-get update
apt-get install -y nginx
echo "Hello World!" > index.html
sudo mv index.html /var/www/html/
sed -i '46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
