#!/usr/bin/env bash
# This script is displaying clock
Hour=1
while [ "$Hour" -lt 13 ]; do
      echo "Hour: $Hour" 	  
        Minute=1
	    while [ "$Minute" -lt 60 ]; do
	    	  echo "$Minute"
		       let Minute=Minute+1
		           done
			       let Hour=Hour+1
			       done
